services:
  api01: &api
    image: renatoelias/pru-async:v3
    container_name: api01
    hostname: api01
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - payment-processor
      - net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '155MB'

  api02:
    <<: *api
    container_name: api02
    hostname: api02


  redis:
    image: redis:7-alpine
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379
    networks:
      - net
    deploy:
      resources:
        limits:
         cpus: '0.1'
         memory: '20MB'

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 9999:9999
    networks:
      - net
    depends_on:
      - redis
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '20MB'

networks:
  payment-processor:
    external: true
  net:
    driver: bridge
