services:
  ruby:
    build:
      context: .
      target: base
    volumes:
      - .:/app
      - rubygems_v3:/usr/local/bundle

  api01: &api
    build:
      context: .
      target: base
    container_name: api01
    hostname: api01
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
      - rubygems_v3:/usr/local/bundle
    networks:
      - payment-processor
      - net
    command: bundle exec falcon serve --bind http://0.0.0.0:3000 -n 4
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '155MB'

  api02:
    <<: *api
    container_name: api02
    hostname: api02

  redis:
    image: redis:7-alpine
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379
    networks:
      - net
    deploy:
      resources:
        limits:
         cpus: '0.1'
         memory: '20MB'

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 9999:9999
    networks:
      - net
    depends_on:
      - redis
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '20MB'
volumes:
  rubygems_v3:

networks:
  payment-processor:
    external: true
  net:
    driver: bridge

