services:
  ruby:
    build:
      context: .
      target: base
    volumes:
      - .:/app
      - rubygems6:/usr/local/bundle

  api01: &api
    build:
      context: .
      target: base
    container_name: api01
    hostname: api01
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
      - rubygems6:/usr/local/bundle
    networks:
      - payment-processor
      - backend
    command: ruby server.rb
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '150MB'

  api02:
    <<: *api
    container_name: api02
    hostname: api02

  redis:
    image: redis:7-alpine
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '50MB'

  traefik:
    image: traefik:v3.1
    container_name: traefik
    command: --configFile=/etc/traefik/traefik.yml
    ports:
      - 9999:9999
    volumes:
      - ./config/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config/traefik/dynamic:/etc/traefik/dynamic:ro
    networks:
      - backend
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '85MB'

volumes:
  rubygems6:
networks:
  payment-processor:
    external: true
  backend:
