services:
  ruby:
    build:
      context: .
      target: base
    volumes:
      - .:/app
      - rubygems_v3:/usr/local/bundle

  api01: &api
    build:
      context: .
      target: base
    container_name: api01
    hostname: api01
    environment:
      - REDIS_URL=redis://redis:6379/0
      - RUBY_GC_HEAP_INIT_SLOTS=20000
      - RUBY_GC_HEAP_FREE_SLOTS=4096
      - RUBY_GC_HEAP_GROWTH_FACTOR=1.2
      - RUBY_GC_HEAP_GROWTH_MAX_SLOTS=30000
    volumes:
      - .:/app
      - rubygems_v3:/usr/local/bundle
    networks:
      - payment-processor
      - net
    command: bundle exec falcon --bind http://0.0.0.0:3000  -n  2 --no-restart  -t 20
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '140MB'

  api02:
    <<: *api
    container_name: api02
    hostname: api02

  redis:
    image: redis:7-alpine
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379
    networks:
      - net
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '30MB'
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 9999:9999
    networks:
      - net
    depends_on:
      - redis
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '40MB'

volumes:
  rubygems_v3:

networks:
  payment-processor:
    external: true
  net:
    driver: bridge