# Static configuration
entryPoints:
  web:
    address: ":9999"

providers:
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

api:
  dashboard: false

log:
  level: INFO

accessLog:
  format: json
  bufferingSize: 0
